config/routes.rb
Jobsworth::Application.routes.draw do

  resources :service_level_agreements, :only => [:create, :destroy, :update]

  resources :services do
    collection do
      get 'auto_complete_for_service_name'
    end
  end

  devise_for  :users, 
              :controllers => { :sessions  => "auth/sessions", 
                                :passwords => "auth/passwords" }

  get 'activities/index', as: 'activities'
  root :to => 'activities#index'

  get '/unified_search' => "customers#search"
  resources :customers do
    collection do
      get 'auto_complete_for_customer_name'
    end
  end

  resources :news_items,  :except => [:show]
  resources :projects,    :except => [:show] do
    get 'list_completed', :on => :collection
  end

  # task routes
  get 'tasks/score/:task_num' => 'tasks#score'
  get 'tasks/:id' => "tasks#edit", :constraints => {:id => /\d+/}
  get "tasks/view/:id" => "tasks#edit", :as => :task_view
  get "tasks/nextTasks/:count" => "tasks#nextTasks", :defaults => { :count => 5 }
  resources :tasks, :except => [:show] do
    collection do
      post 'change_task_weight'
      get  'billable'
    end
  end

  resources :email_addresses, :only => [:update, :edit]

  post "project_files/upload" => "project_files#upload"
  get "project_files/list" => "project_files#list"

  resources :resources do
    collection do
      get :attributes
      get :auto_complete_for_resource_parent
    end
    get :show_password, :on => :member
  end

  resources :resource_types do
    collection do
      get :attribute
    end
  end

  resources :organizational_units

  resources :pages do
    collection do
      get :target_list
    end
  end

  resources :task_filters do
    get :toggle_status, :on => :member
    match :select, :on => :member
    collection do
      get :manage
      get :recent
      get :reset
      get :search
      get :update_current_filter
      get :set_single_task_filter
    end
  end

  resources :todos do
    match :toggle_done, :on => :member
  end

  resources :work_logs do 
    match :update_work_log, :on=> :member
  end

  resources :tags do
    collection do
      get :auto_complete_for_tags
    end
  end

  resources :work do
    collection do
      get :start
      get :stop
      get :cancel
      get :pause
    end
  end

  resources :properties
  resources :scm_projects
  resources :triggers

  match 'api/scm/:provider/:secret_key' => 'scm_changesets#create'
  match ':controller/service.wsdl', :action => 'wsdl'


  get 'projects/:id/ajax_add_permission'      => 'projects#ajax_add_permission'

  resources :projects, :customers, :property_values do
    resources :score_rules
  end

  resources :milestones do
    resources :score_rules

    collection do
      get :get_milestones
      get :list_completed
    end

    member do
      get :revert
      get :complete
    end
  end

  resources :companies do
    resources :score_rules
    member do
      get  :show_logo
      post :delete_logo
    end
    collection do
      post :upload_logo
    end
  end

  match ':controller/list' => ':controller#index'

  match ":controller(/:action(/:id(.:format)))"
end

app/views/resources/_attribute.html.erb
<div class="control-group">
  <% 
     field_id = "attribute_#{ attribute.id }" 
     prefix = "resource[attribute_values][]"
     type = attribute.resource_type_attribute
     same_as_last_type = (type == @last_type)
     @last_type = type
  %> 
  <label for="<%= field_id %>">
    <%= type.name %>
  </label>

  <%= hidden_field_tag("#{ prefix }[resource_type_attribute_id]", type.id, :class => "type_id") %>
  <%= hidden_field_tag "#{ prefix }[id]", attribute.id, :class => "attr_id" %>
  
  <div class="controls">
    <%= value_field(attribute, prefix, field_id, same_as_last_type) %>
  </div>

</div>

app/views/resources/_form.html.erb
<%= form_for(@resource, :html => {:class => "form-horizontal"}) do |f| %>
<fieldset>

  <% if @resource.new_record? %>
    <legend>New Resource</legend>
  <% else %>
    <legend>Edit Resource</legend>
  <% end %>

  <div class="control-group">
    <label for="resource_name"><%= _("Name") %></label>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
  <label for="resource_customer"><%= _("Company") %></label>
    <div class="controls">
      <%= f.hidden_field(:customer_id, :class => "auto_complete_id")  %>
      <%= text_field :resource_customer, :name, { :value => @resource.customer } %>
      <a href="<%= @resource.customer.nil? ? "#" : "/customers/edit/#{@resource.customer.id}" %>" id="resource_customer_link"><i class="icon-share" title="Go to this company"></i></a>
    </div>
  </div>

  <div class="control-group">
    <label for="resource_parent"><%= _("Parent resource") %></label>
    <div class="controls">
      <%= text_field :resource, :parent_id, { :size => 15 } %>
    </div>
  </div>

  <script type= "text/javascript">
    autocomplete('#resource_parent_id',  '/resources/auto_complete_for_resource_parent_id', function(a,b){});
  </script>

  <div class="control-group">
    <label for="resource_type"><%= _("Type") %></label>
    <div class="controls">
      <%= f.select(:resource_type_id, resource_types_options_array, { :include_blank => true }, :onchange => "updateResourceAttributes(this)") %>
    </div>
  </div>

  <div class="control-group">
    <label for="resource_active"><%= ("Active") %></label>
    <div class="controls">
      <%= f.check_box :active%>
    </div>
  </div>

  <div class="control-group">
    <label for="resource_notes"><%= _("Notes") %></label>
    <div class="controls">
      <%= f.text_area :notes, :class => "input-xxlarge" %>
    </div>
  </div>

  <legend><%= _("Attributes") %></legend>
  <div id="attributes">
    <% @resource.all_attributes.each do |ra| %>
      <%= render(:partial => "attribute", :locals => { :attribute => ra }) %> 
    <% end %>
  </div>

  <div class="form-actions">
    <%= cit_submit_tag(@resource) %>
    <% if !@resource.new_record? %>
      <%= link_to(_("Delete"), resource_path(@resource), :method => :delete, :confirm => "Are you sure?", :class => "btn btn-danger") %>
    <% end %>
  </div>
</fieldset>

<% end %>

app/views/resources/_history.html.erb
<div class="history">
  <div class="page_header">
    <%= _("History") %>
  </div>

  <br />

  <% resource.event_logs.each do |log| %>
    <%= history_date_if_needed(log) %>
  
    <div class="hoverrow">
      <div class="avatar">
	<%= avatar_for(log.user, 25) if log.user %>
      </div>
      <div class="time">
	<%= tz.utc_to_local(log.started_at).strftime(current_user.time_format) %>
      </div>
      <div class="body">
	<div class="otheruser">
	  <small>[<%= log.user.name %>]</small>
	</div>
	<%= log.body.html_safe %>
      </div>
    </div>
  <% end %>
</div>

app/views/resources/_querymenu.html.erb
<ul class="querymenu">
  <li>
    <span><%= label %></span>
    <%= add_filter_html(names_and_ids, filter_name, callback) %>
  </li>
</ul>

app/views/resources/_resource.html.erb
<% 
   style = "margin-left: #{ depth * 24 }px" 
   class_name = depth > 0 ? "child depth_#{ depth }" : ""
%>

<li class="<%= class_name %>" style="<%= style %>">
  <%= link_to resource.name, edit_resource_path(resource) %>
</li>
<% child_resources(resource, @resources).each do |r| %>
  <%= render(:partial => "resource", 
  :locals => { :resource => r, :depth => depth + 1 }) %>
<% end %>

app/views/resources/_resource_type.html.erb
<%= resource_type.name %>

app/views/resources/_selected_filter_values.html.erb
<ul class="menu">
  <% if display_all_label != "none" -%>
    <li class="all">
      <%= all_label -%>
    </li>
  <% end -%>
  <% selected_names_and_ids.each do |name, id| -%>
    <li class="cut">
      <%= link_to_function(name, "removeTaskFilter(this)") -%>
      <%= hidden_field_tag("#{ filter_name }[]", id) %>
    </li>
  <% end -%>
</ul>

app/views/resources/_show_password.html.erb
<%
   name = "resource[attribute_values][][password]"
   id = "attribute_#{ @attribute.id }"
%>
<%=
   field = text_field_tag(name, @attribute.password, :id => id, :class => "value",
                           :size => @attribute.resource_type_attribute.default_field_length)
%>

app/views/resources/auto_complete_for_resource_parent_id.html.erb
<ul>
  <% @resources.each do |r| %>
  <li>
    [#<span class="complete_value"><%= r.id %></span>]
    <%= r %>
  </li>
  <% end %>
</ul>

app/views/resources/edit.html.erb
<% @page_title = "Resource: #{@resource.name} - #{$CONFIG[:productName]}" %>

<%= render :partial => "form" %>

<%= render :partial => "history", :locals => { :resource => @resource } %>

app/views/resources/new.html.erb
<% @page_title = "New Resource - #{$CONFIG[:productName]}" %>

<%= render :partial => "form" %>